void gotoxy(int x, int y);
void drawFrame();
void introduction();
void endgame();
void fillthematrix();
void getkey();
void Startgame();
void turndown();
void turnleft();
void turnright();
void turnup();
int a[5][5]={0};
int score=0,check=0;
int checklose=0;
